import type { CSSProperties } from 'react'
import type { Hue, Priority, StatusCategory } from '@/lib/types'

/**
 * Colour is resolved through CSS custom properties rather than Tailwind
 * class names, because hue and status category are runtime values —
 * `bg-${hue}-100` cannot be generated by Tailwind's scanner and would
 * need a safelist that silently rots as the palette changes.
 *
 * Components apply these styles and then use static utility classes
 * like `text-[var(--chip-fg)]`, so the whole palette stays in
 * globals.css and light/dark can never diverge.
 */

export function hueStyle(hue: Hue | undefined): CSSProperties {
  const value = hue ?? 'gray'
  return {
    ['--chip-fg' as string]: `var(--hue-${value})`,
    ['--chip-bg' as string]: `var(--hue-${value}-bg)`,
  }
}

export function hueDot(hue: Hue | undefined): CSSProperties {
  return { backgroundColor: `var(--hue-${hue ?? 'gray'})` }
}

const STATUS_VAR: Record<StatusCategory, string> = {
  backlog: '--status-backlog',
  unstarted: '--status-unstarted',
  started: '--status-started',
  review: '--status-review',
  completed: '--status-completed',
  cancelled: '--status-cancelled',
}

export function statusColor(category: StatusCategory): string {
  return `var(${STATUS_VAR[category]})`
}

const PRIORITY_VAR: Record<Priority, string> = {
  none: '--priority-none',
  low: '--priority-low',
  medium: '--priority-medium',
  high: '--priority-high',
  urgent: '--priority-urgent',
}

export function priorityColor(priority: Priority): string {
  return `var(${PRIORITY_VAR[priority]})`
}
